# Generated by Django 6.0.1 on 2026-01-10 19:16

from django.db import migrations, models
from django.utils.text import slugify


def generate_unique_slugs(apps, schema_editor):
    Conquista = apps.get_model('main', 'Conquista')
    for obj in Conquista.objects.all():
        if not getattr(obj, 'slug', None):
            base = slugify(obj.title)[:190]
            slug = base
            i = 1
            while Conquista.objects.filter(slug=slug).exists():
                slug = f"{base}-{i}"
                i += 1
            obj.slug = slug
            obj.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        # 1) add field without unique constraint so we can populate values
        migrations.AddField(
            model_name='conquista',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Slug'),
        ),
        # 2) populate unique slugs for existing rows
        migrations.RunPython(generate_unique_slugs, reverse_code=migrations.RunPython.noop),
        # 3) alter field to add unique constraint
        migrations.AlterField(
            model_name='conquista',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
