# Generated by Django 6.0.1 on 2026-01-10 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bibliografia', max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Bibliografia',
                'verbose_name_plural': 'Bibliografias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BibliografiaBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block_type', models.CharField(choices=[('paragraph', 'Parágrafo'), ('image', 'Imagem'), ('youtube', 'YouTube (link embed)')], default='paragraph', max_length=20, verbose_name='Tipo')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bibliografia/', verbose_name='Imagem')),
                ('youtube_url', models.CharField(blank=True, help_text='Cole o link do YouTube (ex: https://www.youtube.com/watch?v=...) ou share link.', max_length=400, null=True, verbose_name='URL YouTube')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.bibliografia')),
            ],
            options={
                'verbose_name': 'Bloco de Bibliografia',
                'verbose_name_plural': 'Blocos de Bibliografia',
                'ordering': ['order'],
            },
        ),
    ]
