# Generated by Django 6.0.1 on 2026-01-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bibliografia_bibliografiablock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('image', models.ImageField(upload_to='sponsors/', verbose_name='Imagem')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link (opcional)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'ordering': ['order'],
            },
        ),
    ]
